autonomy/accounts/urls.py
from django.urls import path
from accounts.views import SignUpView


urlpatterns = [
    path('new-user', SignUpView.as_view(), name='signup'),
]

autonomy/autonomy/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('task.urls')),
    path('project/', include('project.urls')),
]

autonomy/project/urls.py
from django.urls import path
from project.views import NewProject

app_name = 'project'
urlpatterns = [
    path('create', NewProject, name='create'),
]

autonomy/task/urls.py
from django.urls import path
from task.views import TaskList, NewTaskView, RemoveTask, PinTask

urlpatterns = [
    path('', TaskList.as_view(), name="task-list-view"),
    path('new', NewTaskView.as_view(), name="task-new"),
    path('remove', RemoveTask, name="task-remove"),
    path('pin', PinTask, name="task-pin"),
]

autonomy/project/models.py
from django.db import models


class Project(models.Model):
    """ Model for a project which holds many tasks

    Properties:
        name - The name of the project
        description (optional) - An overview of the project
        created_at
        updated_at
    """

    name = models.CharField(max_length=100, unique=True)
    description = models.CharField(max_length=10000, blank=True)
    created_at = models.DateTimeField(auto_now=True)
    updated_at = models.DateTimeField(auto_now=True)

autonomy/task/models.py
from django.db import models
from django.forms import ModelForm


# Create your models here.
class Task(models.Model):
    """Model for a single task.

    Properties:
        name - The name/title of the task
        description (optional) - More details on the task
        created_at - The date and time the task was created
        updated_at - The date and time the task was updated
    """

    name = models.CharField(max_length=100, help_text="The name of the task")
    description = models.CharField(max_length=1000, blank=True,
                                   help_text="More details")
    created_at = models.DateTimeField(auto_now=True)
    updated_at = models.DateTimeField(auto_now=True)

    pinned = models.BooleanField(default=False)

    def __str__(self):
        return self.name


class SubTask(models.Model):
    """Model for a subtask.

    Has all properties of Task, plus a relationship to that task
    """

    name = models.CharField(max_length=100, help_text="The name of the task")
    description = models.CharField(max_length=1000, blank=True,
                                   help_text="More details")
    created_at = models.DateTimeField(auto_now=True)
    updated_at = models.DateTimeField(auto_now=True)

    pinned = models.BooleanField(default=False)
    parent_task = models.ForeignKey(Task, on_delete=models.CASCADE)


class TaskForm(ModelForm):
    """Form for a new task"""

    class Meta:
        model = Task
        fields = ['name', 'description']

autonomy/accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views.generic import CreateView


class SignUpView(CreateView):
    """View for creating a user"""

    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'

autonomy/project/views.py
from django.shortcuts import render, redirect
from project.models import Project
from django.views.decorators.csrf import csrf_exempt


@csrf_exempt
def NewProject(request):
    if request.method == 'POST':
        name = request.POST.get('name', None)
        p = Project(name=name)
        p.save()
        return redirect('task-list-view')

autonomy/task/views.py
from django.shortcuts import render, redirect
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy
from task.models import Task, TaskForm


# Create your views here.
class TaskList(ListView):
    """Basic overall view of tasks"""

    model = Task

    def get(self, request):
        """Get and display the list of tasks"""
        tasks = list(self.get_queryset().all().order_by('-created_at'))

        username = None
        auth = request.user.is_authenticated
        if auth:
            username = request.user.username

        # TODO: Optimize
        for task in tasks:
            if task.pinned is True:
                tasks.insert(0, tasks.pop(tasks.index(task)))

        return render(request, 'task/index.html', {'tasks': tasks,
                                                   'auth': auth,
                                                   'username': username})


class NewTaskView(CreateView):
    """Returns a form for a new task"""

    template_name = 'new_task.html'
    form_class = TaskForm
    success_url = reverse_lazy('task-list-view')

    def form_valid(self, form):
        """This method is called when valid form data has been POSTed.
        It should return an HttpResponse.
        """
        form.save()
        return super().form_valid(form)


def RemoveTask(request):
    # Pass id from url tag.
    id = request.POST.get("delete", "")
    task = Task.objects.get(id=id)
    task.delete()

    return redirect('task-list-view')


def PinTask(request):
    # Pass id from url tag
    id = request.POST.get("pin", "")
    task = Task.objects.get(id=id)
    if task.pinned is False:
        task.pinned = True
    else:
        task.pinned = False

    task.save()
    return redirect('task-list-view')

autonomy/task/templates/task/index.html
{% extends 'base.html' %}
{% block title %}Task List{% endblock %}

{% block content %}
{% load static %}

    <!-- Page Content  -->
    <div id="content" class="p-4 p-md-5">

        <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">

            <div class="custom-menu">
            <button type="button" id="sidebarCollapse" class="btn btn-primary">
            </button>
            </div>

            <button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <i class="fa fa-bars"></i>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <input class="form-control" type="text" placeholder="Search" aria-label="Search">
            <ul class="nav navbar-nav ml-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'task-new' %}">New Task</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Contact</a>
                </li>
            </ul>
            </div>
        </div>
        </nav>

        <!-- SASS BUTTON -->

        <!-- <input type="checkbox" class="nav--checkbox" id="nav-toggle">
        <label for="nav-toggle" class="nav--button">
        <span>&nbsp;</span>
        </label>
        <div class="nav--small nav--btn-1">
        <a href="#"><i class="fas fa-star"></i></a>
        </div>
        <div class="nav--small nav--btn-2">
        <a href="#"><i class="fas fa-reply"></i></a>
        </div>
        <div class="nav--small nav--btn-3">
        <a href="#"><i class="fas fa-pen-square"></i></a>
        </div> -->

        <!-- BOOTSTRAP BUTTON -->

        {% if auth == True %}
            <ul class="slides">
                {% for task in tasks %}
                    {% include 'partials/card.html' %}
                {% endfor %}
            </ul>
        {% else %}
        <p>Please sign in to view tasks</p>
        {% endif %}
        </div>
    </div>
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.js"></script>    
    <!-- <script src="js/jquery.min.js"></script> -->
    <script src="{% static 'task/js/script.js' %}"></script>
    <script src="{% static 'task/js/main.js' %}"></script>
{% endblock %}

<!-- https://codepen.io/Snarkie3/pen/XmvRQM -->
<!-- https://codepen.io/iamgarth/pen/oEQgmx -->
<!-- https://codepen.io/WebFikirleri/pen/MLXYKm -->
<!-- https://codepen.io/stephanrusu/pen/QwKLJX -->

autonomy/task/templates/task/list.html
{% extends 'base.html' %}

{% block content %}
{% if auth == True %}
  <h3>To-Do list!</h3>

  <hr>
    {% if tasks %}
    <div class='list'> <!-- This hold all the todo cards. -->
      {% for task in tasks %}
        {% include 'task/partials/card.html' %}
      {% endfor %}
    </div>
      {% else %}
        <p> No tasks to display </p>
    {% endif %}
    <a href="{% url 'task-new' %}"><button>New Task</button></a>
  </hr>
{% else %}
  <p>Please sign in to view to-do list.</p>
{% endif %}
{% endblock %}

autonomy/task/templates/task/new_task.html
{% extends 'base.html' %}

{% block content %}
<h1>Create New Task!</h1>
<form method="post">
  {% csrf_token %}
  {% for field in form %}
    <h3>{{ field.name }}</h3> {{ field.help_text }}:<br/>
    {{ field }}<br/>
  {% endfor %}
    <input type="submit" value="Create Task">
</form>
{% endblock %}

autonomy/task/templates/task/partials/card.html
<li class="slide card w-75">
    <div class="card-body">
      <h5 class="card-title">{{ task.name }}</h5>
      <p class="card-text text-black-50"> 
        {% if task.description %}
        {{ task.description }}
        {% else %}
        No description
        {% endif %}
        {% if task.pinned %}
        <br>
        Pinned
        {% endif %}</p>
      <div class="btn-group-fab" role="group" aria-label="FAB Menu">
        <div>
          <button type="button" class="btn btn-main btn-primary has-tooltip" data-placement="left" title="Menu"> <i class="fa fa-bars"></i> </button>
          <button type="submit" name="pin" form="form-pin" class="btn btn-sub btn-info has-tooltip" value="{{ task.id }}" data-placement="left" title="Pin/Unpin"> <i class="fa fa-map-pin"></i></button>
          <button type="button" class="btn btn-sub btn-danger has-tooltip" data-placement="left" title="Placeholder"> <i class="fa fa-arrows-alt"></i> </button>
          <button type="submit" form="form-delete" name="delete" class="btn btn-sub btn-warning has-tooltip" data-placement="left" value="{{ task.id }}" title="Delete"> <i class="fa fa-trash-o"></i> </button>
          <form id="form-delete" action="{% url 'task-remove' %}" method="post">{% csrf_token %}</form>
          <form id="form-pin" action="{% url 'task-pin' %}" method="post">{% csrf_token %}</form>
        </div>
    </div>
  </li>

autonomy/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <title>{% block title %}Autonomy{% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900" rel="stylesheet">
        
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" href="{% static 'task/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'task/css/main.css' %}">

</head>
<body>
    <div class="wrapper d-flex align-items-stretch">
        <nav id="sidebar">
          <div class="img bg-wrap text-center py-4" style="background-image: url(static/task/images/bg_1.jpg);">
              <div class="user-logo">
                  <div class="img" style="background-image: url(static/task/images/sittingfire.jpg);"></div>
                {% if auth == True %}
                  <h3>{{ username }}</h3>
                {% endif %}
              </div>
          </div>
    <ul class="list-unstyled components mb-5">
      <li class="active">
        <a href="#"><span class="fa fa-home mr-3"></span> Home</a>
      </li>
      <li>
          <a href="#"><span class="fa fa-download mr-3 notif"><small class="d-flex align-items-center justify-content-center">5</small></span>Download</a>
      </li>
      <li>
        <a href="#"><span class="fa fa-gift mr-3"></span> Planner </a>
      </li>
      <li>
        <a href="#"><span class="fa fa-trophy mr-3"></span> Top organizer</a>
      </li>
      <li>
        <a href="#"><span class="fa fa-cog mr-3"></span> Settings</a>
      </li>
      <li>
        <a href="#"><span class="fa fa-support mr-3"></span> Support</a>
      </li>
      {% if auth == True %}
      <li>
        <a href="{% url 'logout' %}"><span class="fa fa-sign-out mr-3"></span> Sign Out</a>
      </li>
      {% else %}
      <li>
        <a href="{% url 'login' %}"><span class="fa fa-sign-out mr-3"></span>Log In</a>
      </li>
      <li>
        <a href="{% url 'signup' %}"><span class="fa fa-sign-out mr-3"></span>Sign Up</a>
      </li>
      {% endif %}
    </ul>

    </nav>
{% block content %}{% endblock %}
</body>
</html>

autonomy/templates/partials/side_bar.html
<form action="{% url 'project:create' %}" method='POST'>
  New project: <input type="text" name='name'>
  <input type="submit" value="Create Project">
  